### ISSUE TITLE
This plasmoid is only for AlphaBlack?

### ISSUE THREAD

**Issue by roachsinai** [Zren/plasma-applet-alphablackcontrol#3]
> v5 Requires: Breeze AlphaBlack v14+ (https://store.kde.org/p/1084931/)

As discribe at kde store.

**Comment by Zren** [comment]
That is correct. This widget modifies the `~/.local/share/plasma/desktoptheme/breeze-alphablack` folder, then switches to `breeze-dark` and back to `breeze-alphablack` to force Plasma to reload the theme. It does this by editing `[Theme] name=breeze-alphablack` in `~/.config/plasmarc`.

**Comment by roachsinai** [comment]
Ok, thanks!
