### ISSUE TITLE
Should alphablackcontrol plasmoid icon more brighter?

### ISSUE THREAD

**Issue by roachsinai** [Zren/plasma-applet-alphablackcontrol#4]
The waterdrop icon is so good, but I think it hard to find it.

And thanks for this control and Theme alphablack!

**Comment by Zren** [comment]
The icon is `color-picker-black` and follows your color scheme's text color (with breeze icons at least).

![2019-03-11___02-38-09](https://user-images.githubusercontent.com/416367/54104808-7e5af380-43a7-11e9-90d1-ea63c4861de4.png)

**Comment by roachsinai** [comment]
Okay, thanks again.
