### ISSUE TITLE
command kquitapp5 plasmashell && kstart5 plasmashell got an TypeError

### ISSUE THREAD

**Issue by roachsinai** [Zren/plasma-applet-alphablackcontrol#5]
`file:///home/roach/.local/share/plasma/plasmoids/com.github.zren.alphablackcontrol/contents/ui/Main.qml:89: TypeError: Cannot call method 'updateConfigBindings' of null`.

**Comment by Zren** [comment]
Already fixed with https://github.com/Zren/plasma-applet-alphablackcontrol/commit/ed84371ccf295c90aa2cd3fdca393281fda276e2 and will be gone in v6. I guess I should release it.

**Comment by roachsinai** [comment]
Ok, yeah! Thanks and pls, lol.

**Comment by Zren** [comment]
Uploaded v6 of alphablackcontrol. Make sure to also update breeze-alphablack to v16.

**Comment by roachsinai** [comment]
![image](https://user-images.githubusercontent.com/9500049/76730915-31b6af00-6797-11ea-882a-362192d153e4.png)

Thanks for your updates. But the icon of Alphablack Control cannot hide now.

So didn't hide is what you expected, or something wrong on my Manjaro?

**Comment by Zren** [comment]
https://store.kde.org/p/1237963/

> Plasma 5.18+
> Right click the systray triangle > Configure System Tray
> Find "AlphaBlack Control" > Change "Show when relevant" to "Disabled"

Plasma 5.18 changed how you edit the panel. There is not currently a way for widgets to detect when you are editing the panel. Nor is there a way to detect if the user is running Plasma 5.18 or Plasma 5.17, so I can't use a unique message for each.

**Comment by roachsinai** [comment]
Ok, thanks a lot.
